# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('prerequisites', models.ManyToManyField(blank=True, to='learning_outcomes.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='learning_outcomes.TopicStructure')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_outcomes.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
