# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_outcomes', '0002_add_outcomes_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
